name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - seaborn=0.11.2
  - pandas=1.4.4
  - matplotlib=3.2.2
  - pip=22.1.2
  - pandas-profiling=3.2.0
  - pyarrow=8.0.0
  - pydantic=1.8.2
  - protobuf
  - pip:
      - wandb==0.13.2

